### ISSUE TITLE
Adding PHP-XML to the egg

### ISSUE THREAD

**Issue by augesrob** [finnie2006/ptero-eggs#11]
PHP exif_imagetype
  PHP XML 
  
  https://i.gyazo.com/c8ed77e5ca21a2d70deaf99d7da4fd45.png

**Comment by finnie2006** [comment]
This will get included in the egg this week

**Comment by augesrob** [comment]
> This will get included in the egg this week

How is it going? I know everyone has a personal life as well.

**Comment by finnie2006** [comment]
@augesrob try it now

**Comment by finnie2006** [comment]
?

**Comment by augesrob** [comment]
Works awesome, Thanks for the update!

**Comment by finnie2006** [comment]
Nice 👍🏻
