### ISSUE TITLE
PHP-Xml missing 

### ISSUE THREAD

**Issue by MrJuju0319** [finnie2006/ptero-eggs#12]
Hello 
Im using an website but /
REQUIREMENTS : 
A web-host with PHP 7.1 or greater
PHP modules: mbstring, php-xml, openssl, curl
PHP config: url_allow_fopen enabled

Can you check this

**Comment by MrJuju0319** [comment]
![image](https://user-images.githubusercontent.com/16257583/171214851-9cba0483-566d-48fb-b163-538545cf3b49.png)

**Comment by MrJuju0319** [comment]
I do not understand why the site tells me that it is missing

**Comment by MrJuju0319** [comment]
Résolve, i dont use docker and eges 🤣

**Comment by finnie2006** [comment]
Officialy the wierdest github issue
