### ISSUE TITLE
XML missing 

### ISSUE THREAD

**Issue by log1n228** [finnie2006/ptero-eggs#14]
Missing SimpleXML
I know that SimpleXML is included in php8-xml but it's still not there
![image](https://user-images.githubusercontent.com/76619779/177176102-fe306641-8544-4f21-99a0-e30510e8cd70.png) 
(This error appears because the SimpleXMLElement class is missing.)

**Comment by finnie2006** [comment]
Should be fixed in the latest release, if not then make a new issue!
