### ISSUE TITLE
Simplified installation by installing Nexcloud directly into Webroot

### ISSUE THREAD

**Issue by IkiaeM** [finnie2006/ptero-eggs#17]
Simplified installation by installing Nexcloud directly into Webroot.

Here is an adaptation of the installation of the egg:

```
#!/bin/ash

cd /mnt/server

apk --update add git

git clone --branch Nextcloud https://github.com/finnie2006/ptero-nginx ./temp

cp -r ./temp/nginx /mnt/server/
cp -r ./temp/php-fpm /mnt/server/
cp ./temp/start.sh /mnt/server/

wget -P ./temp https://download.nextcloud.com/server/releases/latest.zip
unzip -q ./temp/latest.zip -d ./temp/
mv ./temp/nextcloud ./webroot

chmod +x /mnt/server/start.sh

rm -rf ./temp
```

I no longer need the "webroot" folder on your Github repo. I download the last version of NC, I extract it and I move by renaming the nextcloud folder at the root to webroot and at the first launch we have to create an admin user and connect a database which I think is easier.

In part it was impossible to install NC at the root of webroot because there was a conflict with your file "index.php" and I think it's not interesting to propose the location because there is nothing next to it so we might as well do it directly at the root and automatically. I let you see my code and modify your egg if you want.

**Comment by finnie2006** [comment]
Thanks for your suggestion, I'm going to test it out today and implement it before my vacation tomorrow.

**Comment by finnie2006** [comment]
![afbeelding](https://user-images.githubusercontent.com/57916807/183065062-9ecbcb83-2a44-4db4-bbfe-1d5e02d50108.png)
at first testing it seems like the files are not loading

**Comment by IkiaeM** [comment]
Did you find the reason for this?

**Comment by IkiaeM** [comment]
The problem does not seem to come from my modification because I get the same error in both cases (the same as you have)

**Comment by finnie2006** [comment]
That was the reason I removed it from ptero market

**Comment by IkiaeM** [comment]
I can't find any solution and I'm a bit disgusted... I hope you'll look at it when you come back to see if you can find a solution... But everything seems fine...

**Comment by finnie2006** [comment]
Going to close the issue then as i already tried this

**Comment by IkiaeM** [comment]
Have you tried using the official docker? And adapt it?

**Comment by finnie2006** [comment]
Closing for now as it is leading to a dead end for now
