### ISSUE TITLE
Sessions doesn't work

### ISSUE THREAD

**Issue by jakubhyza** [finnie2006/ptero-eggs#18]
# Sessions doesn't work

**Description**
I was trying to install Nameless mc inside the container. 
I was unable to install it. Error log shows this message:

`/home/container/webroot/core/init.php(18): Call to undefined function session_start()`

**How to replicate the issue**
I tried to create test.php file just with session_start() command and get ERROR 500 as the result.
Console output was:
`[error] 25#25: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function session_start() in /home/container/webroot/test.php:3`

I run `php -m` and I can't see session. Looks like sessions are not installed in the container even if I know there is `apk add php8-session` inside the docker file.

Can you help me please to fix this issue? Thank you.

**Comment by BasToTheMax** [comment]
has this been fixed?

**Comment by finnie2006** [comment]
You are using the wrong docker image

**Comment by Prefix** [comment]
8.0 tag works fine, thanks.

**Comment by finnie2006** [comment]
Great!, please note that the latest tag is not getting updated anymore so use the 8.X tags
