### ISSUE TITLE
Php version

### ISSUE THREAD

**Issue by anondev-sudo** [finnie2006/ptero-eggs#4]
Add option to choose php version (docker image)

**Comment by finnie2006** [comment]
Wich version do you want

**Comment by anondev-sudo** [comment]
7.4, 8.0 php versions


Also is composer supported there?

**Comment by chezzzer** [comment]
Any update on composer?

**Comment by finnie2006** [comment]
No, maybe we will look into it

**Comment by chezzzer** [comment]
I would love to see this as I have been needing composer libraries and have had to decompile them myself to integrate into this.

**Comment by finnie2006** [comment]
@chezzzer Compooser just got added

**Comment by Guest0070** [comment]
Any update on PHP 7.4?

**Comment by finnie2006** [comment]
No plans on adding it right now, as most projects etc support php 8
