### ISSUE TITLE
Problem with PHP FPM

### ISSUE THREAD

**Issue by ElBrigos** [finnie2006/ptero-eggs#8]
Hello, i have a problem with the last update of the repo, have you a solution ?

Starting PHP-FPM...
./start.sh: line 4: /usr/sbin/php-fpm8.1: not found

**Comment by finnie2006** [comment]
Try this

#!/bin/ash

echo "Starting PHP-FPM..."
/usr/sbin/php-fpm8 --fpm-config /home/container/php-fpm/php-fpm.conf --daemonize

echo "Starting Nginx..."
/usr/sbin/nginx -c /home/container/nginx/nginx.conf

**Comment by ElBrigos** [comment]
Mhhhhhh...... Work ! thanks for your help ;)
